<!DOCTYPE HTML>
<html lang="zh-CN">


<head><meta name="generator" content="Hexo 3.9.0">
    <meta charset="utf-8">
    <meta name="keywords" content="Shiroの基础知识, kalifun;blog.kalifun">
    <meta name="description" content="Shiroの基础知识Authenticator(用户认证)
用户认证，用户去访问系统，系统要验证用户身份的合法性
认证方法 最常用的用户身份验证的方法：1、用户名密码方式、2、指纹打卡机、3、基于证书验证方法。。系统验证用户身份合法，用户方">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=no">
    <meta name="renderer" content="webkit|ie-stand|ie-comp">
    <meta name="mobile-web-app-capable" content="yes">
    <meta name="format-detection" content="telephone=no">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="apple-mobile-web-app-status-bar-style" content="black-translucent">
    <title>Shiroの基础知识 | kalifun</title>
    <link rel="icon" type="image/png" href="/favicon.png">

    <link rel="stylesheet" type="text/css" href="/libs/awesome/css/all.css">
    <link rel="stylesheet" type="text/css" href="/libs/materialize/materialize.min.css">
    <link rel="stylesheet" type="text/css" href="/libs/aos/aos.css">
    <link rel="stylesheet" type="text/css" href="/libs/animate/animate.min.css">
    <link rel="stylesheet" type="text/css" href="/libs/lightGallery/css/lightgallery.min.css">
    <link rel="stylesheet" type="text/css" href="/css/matery.css">
    <link rel="stylesheet" type="text/css" href="/css/my.css">
    <style type="text/css">
        
    </style>

    <script src="/libs/jquery/jquery-2.2.0.min.js"></script>
    
<link rel="stylesheet" href="/css/prism-tomorrow.css" type="text/css"></head>


<body>
    <header class="navbar-fixed">
    <nav id="headNav" class="bg-color nav-transparent">
        <div id="navContainer" class="nav-wrapper head-container">
            <div class="brand-logo">
                <a href="/" class="waves-effect waves-light">
                    
                    <img src="/medias/logo.png" class="logo-img" alt="LOGO">
                    
                    <span class="logo-span">kalifun</span>
                </a>
            </div>
            

<a href="#" data-target="mobile-nav" class="sidenav-trigger button-collapse"><i class="fas fa-bars"></i></a>
<ul class="right nav-menu">
  
  <li class="hide-on-med-and-down nav-item">
    
    <a href="/" class="waves-effect waves-light">
      
      <i class="fas fa-home" style="zoom: 0.6;"></i>
      
      <span>首页</span>
    </a>
    
  </li>
  
  <li class="hide-on-med-and-down nav-item">
    
    <a href="/tags" class="waves-effect waves-light">
      
      <i class="fas fa-tags" style="zoom: 0.6;"></i>
      
      <span>标签</span>
    </a>
    
  </li>
  
  <li class="hide-on-med-and-down nav-item">
    
    <a href="/categories" class="waves-effect waves-light">
      
      <i class="fas fa-bookmark" style="zoom: 0.6;"></i>
      
      <span>分类</span>
    </a>
    
  </li>
  
  <li class="hide-on-med-and-down nav-item">
    
    <a href="/archives" class="waves-effect waves-light">
      
      <i class="fas fa-archive" style="zoom: 0.6;"></i>
      
      <span>归档</span>
    </a>
    
  </li>
  
  <li class="hide-on-med-and-down nav-item">
    
    <a href="/about" class="waves-effect waves-light">
      
      <i class="fas fa-user-circle" style="zoom: 0.6;"></i>
      
      <span>关于</span>
    </a>
    
  </li>
  
  <li class="hide-on-med-and-down nav-item">
    
    <a href="/friends" class="waves-effect waves-light">
      
      <i class="fas fa-address-book" style="zoom: 0.6;"></i>
      
      <span>友情链接</span>
    </a>
    
  </li>
  
  <li>
    <a href="#searchModal" class="modal-trigger waves-effect waves-light">
      <i id="searchIcon" class="fas fa-search" title="搜索" style="zoom: 0.85;"></i>
    </a>
  </li>
</ul>

<div id="mobile-nav" class="side-nav sidenav">

    <div class="mobile-head bg-color">
        
        <img src="/medias/logo.png" class="logo-img circle responsive-img">
        
        <div class="logo-name">kalifun</div>
        <div class="logo-desc">
            
            既然已经决定做一件事，那么除了当初决定做这件事的我之外，没人可以叫我傻瓜。
            
        </div>
    </div>

    

    <ul class="menu-list mobile-menu-list">
        
<li class="m-nav-item">
			
				<a href="/" class="waves-effect waves-light">
					
					<i class="fa-fw fas fa-home"></i>
					
					首页
				</a>
          
        </li>
        
<li class="m-nav-item">
			
				<a href="/tags" class="waves-effect waves-light">
					
					<i class="fa-fw fas fa-tags"></i>
					
					标签
				</a>
          
        </li>
        
<li class="m-nav-item">
			
				<a href="/categories" class="waves-effect waves-light">
					
					<i class="fa-fw fas fa-bookmark"></i>
					
					分类
				</a>
          
        </li>
        
<li class="m-nav-item">
			
				<a href="/archives" class="waves-effect waves-light">
					
					<i class="fa-fw fas fa-archive"></i>
					
					归档
				</a>
          
        </li>
        
<li class="m-nav-item">
			
				<a href="/about" class="waves-effect waves-light">
					
					<i class="fa-fw fas fa-user-circle"></i>
					
					关于
				</a>
          
        </li>
        
<li class="m-nav-item">
			
				<a href="/friends" class="waves-effect waves-light">
					
					<i class="fa-fw fas fa-address-book"></i>
					
					友情链接
				</a>
          
        </li>
        
        
        <li><div class="divider"></div></li>
        <li>
            <a href="https://github.com/kalifun" class="waves-effect waves-light" target="_blank">
                <i class="fab fa-github-square fa-fw"></i>Fork Me
            </a>
        </li>
        
    </ul>
</div>

        </div>

        
            <style>
    .nav-transparent .github-corner {
        display: none !important;
    }

    .github-corner {
        position: absolute;
        z-index: 10;
        top: 0;
        right: 0;
        border: 0;
        transform: scale(1.1);
    }

    .github-corner svg {
        color: #0f9d58;
        fill: #fff;
        height: 64px;
        width: 64px;
    }

    .github-corner:hover .octo-arm {
        animation: a 0.56s ease-in-out;
    }

    .github-corner .octo-arm {
        animation: none;
    }

    @keyframes a {
        0%,
        to {
            transform: rotate(0);
        }
        20%,
        60% {
            transform: rotate(-25deg);
        }
        40%,
        80% {
            transform: rotate(10deg);
        }
    }
</style>

<a href="https://github.com/kalifun" class="github-corner tooltipped hide-on-med-and-down" target="_blank"
   data-tooltip="Fork Me" data-position="left" data-delay="50">
    <svg viewBox="0 0 250 250" aria-hidden="true">
        <path d="M0,0 L115,115 L130,115 L142,142 L250,250 L250,0 Z"></path>
        <path d="M128.3,109.0 C113.8,99.7 119.0,89.6 119.0,89.6 C122.0,82.7 120.5,78.6 120.5,78.6 C119.2,72.0 123.4,76.3 123.4,76.3 C127.3,80.9 125.5,87.3 125.5,87.3 C122.9,97.6 130.6,101.9 134.4,103.2"
              fill="currentColor" style="transform-origin: 130px 106px;" class="octo-arm"></path>
        <path d="M115.0,115.0 C114.9,115.1 118.7,116.5 119.8,115.4 L133.7,101.6 C136.9,99.2 139.9,98.4 142.2,98.6 C133.8,88.0 127.5,74.4 143.8,58.0 C148.5,53.4 154.0,51.2 159.7,51.0 C160.3,49.4 163.2,43.6 171.4,40.1 C171.4,40.1 176.1,42.5 178.8,56.2 C183.1,58.6 187.2,61.8 190.9,65.4 C194.5,69.0 197.7,73.2 200.1,77.6 C213.8,80.2 216.3,84.9 216.3,84.9 C212.7,93.1 206.9,96.0 205.4,96.6 C205.1,102.4 203.0,107.8 198.3,112.5 C181.9,128.9 168.3,122.5 157.7,114.1 C157.9,116.9 156.7,120.9 152.7,124.9 L141.0,136.5 C139.8,137.7 141.6,141.9 141.8,141.8 Z"
              fill="currentColor" class="octo-body"></path>
    </svg>
</a>
        
    </nav>

</header>

    



<div class="bg-cover pd-header post-cover" style="background-image: url('/medias/featureimages/7.jpg')">
    <div class="container" style="right: 0px;left: 0px;">
        <div class="row">
            <div class="col s12 m12 l12">
                <div class="brand">
                    <div class="description center-align post-title">
                        Shiroの基础知识
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>




<main class="post-container content">

    
    <link rel="stylesheet" href="/libs/tocbot/tocbot.css">
<style>
    #articleContent h1::before,
    #articleContent h2::before,
    #articleContent h3::before,
    #articleContent h4::before,
    #articleContent h5::before,
    #articleContent h6::before {
        display: block;
        content: " ";
        height: 100px;
        margin-top: -100px;
        visibility: hidden;
    }

    #articleContent :focus {
        outline: none;
    }

    .toc-fixed {
        position: fixed;
        top: 64px;
    }

    .toc-widget {
        padding-left: 20px;
    }

    .toc-widget .toc-title {
        margin: 35px 0 15px 0;
        padding-left: 17px;
        font-size: 1.5rem;
        font-weight: bold;
        line-height: 1.5rem;
    }

    .toc-widget ol {
        padding: 0;
        list-style: none;
    }

    #toc-content ol {
        padding-left: 10px;
    }

    #toc-content ol li {
        padding-left: 10px;
    }

    #toc-content .toc-link:hover {
        color: #42b983;
        font-weight: 700;
        text-decoration: underline;
    }

    #toc-content .toc-link::before {
        background-color: transparent;
        max-height: 25px;
    }

    #toc-content .is-active-link {
        color: #42b983;
    }

    #toc-content .is-active-link::before {
        background-color: #42b983;
    }

    #floating-toc-btn {
        position: fixed;
        right: 15px;
        bottom: 76px;
        padding-top: 15px;
        margin-bottom: 0;
        z-index: 998;
    }

    #floating-toc-btn .btn-floating {
        width: 48px;
        height: 48px;
    }

    #floating-toc-btn .btn-floating i {
        line-height: 48px;
        font-size: 1.4rem;
    }
</style>
<div class="row">
    <div id="main-content" class="col s12 m12 l9">
        <!-- 文章内容详情 -->
<div id="artDetail">
    <div class="card">
        <div class="card-content article-info">
            <div class="row tag-cate">
                <div class="col s7">
                    
                    <div class="article-tag">
                        
                            <a href="/tags/springboot/">
                                <span class="chip bg-color">springboot</span>
                            </a>
                        
                    </div>
                    
                </div>
                <div class="col s5 right-align">
                    
                    <div class="post-cate">
                        <i class="fas fa-bookmark fa-fw icon-category"></i>
                        
                            <a href="/categories/Java/" class="post-category">
                                Java
                            </a>
                        
                    </div>
                    
                </div>
            </div>

            <div class="post-info">
                <div class="post-date info-break-policy">
                    <i class="far fa-calendar-minus fa-fw"></i>发布日期:&nbsp;&nbsp;
                    2019-05-08
                </div>

                
                    
                    <div class="info-break-policy">
                        <i class="far fa-file-word fa-fw"></i>文章字数:&nbsp;&nbsp;
                        2.7k
                    </div>
                    

                    
                    <div class="info-break-policy">
                        <i class="far fa-clock fa-fw"></i>阅读时长:&nbsp;&nbsp;
                        14 分
                    </div>
                    
                
				
				
                    <div id="busuanzi_container_page_pv" class="info-break-policy">
                        <i class="far fa-eye fa-fw"></i>阅读次数:&nbsp;&nbsp;
                        <span id="busuanzi_value_page_pv"></span>
                    </div>
				
            </div>
        </div>
        <hr class="clearfix">
        <div class="card-content article-card-content">
            <div id="articleContent">
                <h1 id="Shiroの基础知识"><a href="#Shiroの基础知识" class="headerlink" title="Shiroの基础知识"></a>Shiroの基础知识</h1><h2 id="Authenticator-用户认证"><a href="#Authenticator-用户认证" class="headerlink" title="Authenticator(用户认证)"></a>Authenticator(用户认证)</h2><blockquote>
<h3 id="用户认证，用户去访问系统，系统要验证用户身份的合法性"><a href="#用户认证，用户去访问系统，系统要验证用户身份的合法性" class="headerlink" title="用户认证，用户去访问系统，系统要验证用户身份的合法性"></a>用户认证，用户去访问系统，系统要验证用户身份的合法性</h3></blockquote>
<h2 id="认证方法"><a href="#认证方法" class="headerlink" title="认证方法"></a>认证方法</h2><p> 最常用的用户身份验证的方法：1、用户名密码方式、2、指纹打卡机、3、基于证书验证方法。。系统验证用户身份合法，用户方可访问系统的资源。</p>
<h2 id="认证流程"><a href="#认证流程" class="headerlink" title="认证流程"></a>认证流程</h2><ul>
<li>创建一个简单的Realm（Realm 充当了 Shiro 与应用安全数据间的“桥梁”或者“连接器”。）</li>
<li>创建一个SecurityManager </li>
<li>subject主体发送请求</li>
<li>用户名密码认证</li>
<li>Authenticator认证</li>
<li>Realm验证数据<h2 id="测试Code"><a href="#测试Code" class="headerlink" title="测试Code"></a>测试Code</h2><pre><code>package com.imgurl;
</code></pre></li>
</ul>
<p>import org.apache.shiro.SecurityUtils;<br>import org.apache.shiro.authc.UsernamePasswordToken;<br>import org.apache.shiro.mgt.DefaultSecurityManager;<br>import org.apache.shiro.realm.SimpleAccountRealm;<br>import org.apache.shiro.subject.Subject;<br>import org.junit.Before;<br>import org.junit.Test;</p>
<p>public class Authrnrization {<br>//    创建realm<br>    SimpleAccountRealm simpleAccountRealm = new SimpleAccountRealm();</p>
<pre><code>@Before
public void  add() {
    simpleAccountRealm.addAccount(&quot;admin&quot;,&quot;12345&quot;);
}


@Test
public void checkauthrization(){</code></pre><p>//        1.创建一个管理器<br>        DefaultSecurityManager defaultSecurityManager = new DefaultSecurityManager();<br>        defaultSecurityManager.setRealm(simpleAccountRealm);</p>
<p>//        2.主体发动请求<br>        SecurityUtils.setSecurityManager(defaultSecurityManager);<br>        Subject subject = SecurityUtils.getSubject();</p>
<p>//        3.认证<br>        UsernamePasswordToken token = new UsernamePasswordToken(“admin”,”12345”);<br>        subject.login(token);</p>
<pre><code>    System.out.println(&quot;认证：&quot;+subject.isAuthenticated());
}</code></pre><p>}</p>
<pre><code>## Authorizer(用户授权)
&gt; 用户授权，简单理解为访问控制，在用户认证通过后，系统对用户访问资源进行控制，用户具有资源的访问权限方可访问。
## 授权流程
-  创建一个SecurityManager 
-  主体授权
-  SecurityManager授权
-  Authorizer授权
-  Realm获取用户角色权限数据
## 测试Code</code></pre><p>package com.imgurl;</p>
<p>import org.apache.shiro.SecurityUtils;<br>import org.apache.shiro.authc.UsernamePasswordToken;<br>import org.apache.shiro.mgt.DefaultSecurityManager;<br>import org.apache.shiro.realm.SimpleAccountRealm;<br>import org.apache.shiro.subject.Subject;<br>import org.junit.Before;<br>import org.junit.Test;</p>
<p>public class roles {<br>    SimpleAccountRealm simpleAccountRealm = new SimpleAccountRealm();<br>    @Before<br>    public void add() {<br>        simpleAccountRealm.addAccount(“admin”,”12345”,”Manager”,”Otheruser”);<br>    }</p>
<pre><code>@Test
public void Authorizer(){
    //    1.创建securityManager
    DefaultSecurityManager defaultSecurityManager = new DefaultSecurityManager();
    defaultSecurityManager.setRealm(simpleAccountRealm);</code></pre><p>//        2.主体发送请求授权<br>        SecurityUtils.setSecurityManager(defaultSecurityManager);<br>        Subject subject = SecurityUtils.getSubject();</p>
<p>//        3.authorizer授权<br>        UsernamePasswordToken token = new UsernamePasswordToken(“admin”,”12345”);<br>        subject.login(token);<br>        System.out.println(“认证：”+subject.isAuthenticated());<br>        subject.checkRoles(“Manager”,”Otheruser”);<br>    }<br>}</p>
<pre><code>## Realm
&gt; ###   Realm: 域，Shiro 从 Realm 中获取用户，角色，权限信息。可以把 Relam 看成 DataSource，即安全数据源。
 前面我们使用的是SimpleAccountRealm，并通过addAccount来预设用户信息。
### IniRealm
&gt; IniRealm 顾名思义，即通过读取 .ini 文件来获取用户，角色，权限信息。
 创建xxx.ini文件(在Test目录下创建resource)</code></pre><p>[users]<br>admin = 123456,Manager<br>fun = 123456,Otheruser<br>用户名 = 密码,角色<br>[roles]<br>Manager = user:delete,user:add,user:update,user:select<br>Otheruser = user:select<br>角色 = 权限</p>
<pre><code>#### 测试Code</code></pre><p>package com.imgurl;</p>
<p>import org.apache.shiro.SecurityUtils;<br>import org.apache.shiro.authc.AuthenticationException;<br>import org.apache.shiro.authc.UsernamePasswordToken;<br>import org.apache.shiro.mgt.DefaultSecurityManager;<br>import org.apache.shiro.realm.text.IniRealm;<br>import org.apache.shiro.subject.Subject;<br>import org.junit.Test;</p>
<p>import java.util.Arrays;</p>
<p>public class IniRealmTest {<br>    @Test<br>    public void IniRealm(){</p>
<pre><code>    DefaultSecurityManager defaultSecurityManager = new DefaultSecurityManager();
    IniRealm iniRealm = new IniRealm(&quot;classpath:shiro.ini&quot;);
    defaultSecurityManager.setRealm(iniRealm);

    SecurityUtils.setSecurityManager(defaultSecurityManager);
    Subject subject = SecurityUtils.getSubject();

    UsernamePasswordToken token = new UsernamePasswordToken(&quot;fun&quot;,&quot;123456&quot;);
    try {
        subject.login(token);
        System.out.println(&quot;Authenticator:&quot;+subject.isAuthenticated());
        System.out.println(&quot;登陆成功&quot;);
    }catch (AuthenticationException e){
        e.printStackTrace();
        System.out.println(&quot;认证失败&quot;);
    }

    System.out.println(&quot;--------角色验证---------&quot;);
    System.out.println(&quot;是否具备Manger权限：&quot;+subject.hasRole(&quot;Manager&quot;));
    System.out.println(&quot;是否具备Otheruser权限：&quot;+subject.hasRole(&quot;Otheruser&quot;));
    System.out.println(&quot;是否同事具备Manger和Otheruser权限：&quot;+subject.hasAllRoles(Arrays.asList(&quot;Manager&quot;,&quot;Otheruser&quot;)));

    System.out.println(&quot;---------权限------------&quot;);
    System.out.println(&quot;是否具备user:select权限：&quot;+subject.isPermitted(&quot;user:select&quot;));
    System.out.println(&quot;是否具备user:add权限：&quot;+subject.isPermitted(&quot;user:add&quot;));
    System.out.println(&quot;是否具备user:delete权限：&quot;+subject.isPermitted(&quot;user:delete&quot;));
    System.out.println(&quot;是否具备user:update权限：&quot;+subject.isPermitted(&quot;user:update&quot;));
}</code></pre><p>}</p>
<pre><code></code></pre><p>Authenticator:true<br>登陆成功<br>——–角色验证———<br>是否具备Manger权限：false<br>是否具备Otheruser权限：true<br>是否同事具备Manger和Otheruser权限：false<br>———权限————<br>是否具备user:select权限：true<br>是否具备user:add权限：false<br>是否具备user:delete权限：false<br>是否具备user:update权限：false</p>
<pre><code>### JdbcRealm
&gt; dbcRelam 顾名思义，即通过通过访问数据库来获取用户，角色，权限信息。
#### 创建数据</code></pre><hr>
<p>– 主机:                           127.0.0.1<br>– 服务器版本:                        10.3.10-MariaDB - mariadb.org binary distribution<br>– 服务器操作系统:                      Win64<br>– HeidiSQL 版本:                  9.4.0.5125</p>
<hr>
<p>/<em>!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;<br>/</em>!40101 SET NAMES utf8 <em>/;<br>/</em>!50503 SET NAMES utf8mb4 <em>/;<br>/</em>!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 <em>/;<br>/</em>!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE=’NO_AUTO_VALUE_ON_ZERO’ */;</p>
<p>– 导出  表 funimg.roles_permissions 结构<br>CREATE TABLE IF NOT EXISTS <code>roles_permissions</code> (<br>  <code>id</code> bigint(20) NOT NULL AUTO_INCREMENT,<br>  <code>role_name</code> varchar(100) DEFAULT NULL,<br>  <code>permission</code> varchar(100) DEFAULT NULL,<br>  PRIMARY KEY (<code>id</code>),<br>  UNIQUE KEY <code>idx_roles_permissions</code> (<code>role_name</code>,<code>permission</code>)<br>) ENGINE=InnoDB AUTO_INCREMENT=8 DEFAULT CHARSET=utf8;</p>
<p>– 正在导出表  funimg.roles_permissions 的数据：~5 rows (大约)<br>/<em>!40000 ALTER TABLE <code>roles_permissions</code> DISABLE KEYS */;<br>INSERT INTO <code>roles_permissions</code> (<code>id</code>, <code>role_name</code>, <code>permission</code>) VALUES<br>    (6, ‘Manager’, ‘user:add’),<br>    (1, ‘Manager’, ‘user:delete’),<br>    (2, ‘Manager’, ‘user:select’),<br>    (5, ‘Manager’, ‘user:update’),<br>    (7, ‘Otheruser’, ‘user:select’);<br>/</em>!40000 ALTER TABLE <code>roles_permissions</code> ENABLE KEYS */;</p>
<p>– 导出  表 funimg.users 结构<br>CREATE TABLE IF NOT EXISTS <code>users</code> (<br>  <code>id</code> bigint(20) NOT NULL AUTO_INCREMENT,<br>  <code>username</code> varchar(100) DEFAULT NULL,<br>  <code>password</code> varchar(100) DEFAULT NULL,<br>  <code>password_salt</code> varchar(100) DEFAULT NULL,<br>  PRIMARY KEY (<code>id</code>),<br>  UNIQUE KEY <code>idx_users_username</code> (<code>username</code>)<br>) ENGINE=InnoDB AUTO_INCREMENT=3 DEFAULT CHARSET=utf8;</p>
<p>– 正在导出表  funimg.users 的数据：~2 rows (大约)<br>/<em>!40000 ALTER TABLE <code>users</code> DISABLE KEYS */;<br>INSERT INTO <code>users</code> (<code>id</code>, <code>username</code>, <code>password</code>, <code>password_salt</code>) VALUES<br>    (1, ‘admin’, ‘123456’, NULL),<br>    (2, ‘fun’, ‘123456’, NULL);<br>/</em>!40000 ALTER TABLE <code>users</code> ENABLE KEYS */;</p>
<p>– 导出  表 funimg.user_roles 结构<br>CREATE TABLE IF NOT EXISTS <code>user_roles</code> (<br>  <code>id</code> bigint(20) NOT NULL AUTO_INCREMENT,<br>  <code>username</code> varchar(100) DEFAULT NULL,<br>  <code>role_name</code> varchar(100) DEFAULT NULL,<br>  PRIMARY KEY (<code>id</code>),<br>  UNIQUE KEY <code>idx_user_roles</code> (<code>username</code>,<code>role_name</code>)<br>) ENGINE=InnoDB AUTO_INCREMENT=3 DEFAULT CHARSET=utf8;</p>
<p>– 正在导出表  funimg.user_roles 的数据：~2 rows (大约)<br>/<em>!40000 ALTER TABLE <code>user_roles</code> DISABLE KEYS */;<br>INSERT INTO <code>user_roles</code> (<code>id</code>, <code>username</code>, <code>role_name</code>) VALUES<br>    (1, ‘admin’, ‘Manager’),<br>    (2, ‘fun’, ‘Otheruser’);<br>/</em>!40000 ALTER TABLE <code>user_roles</code> ENABLE KEYS */;</p>
<p>/<em>!40101 SET SQL_MODE=IFNULL(@OLD_SQL_MODE, ‘’) */;<br>/</em>!40014 SET FOREIGN_KEY_CHECKS=IF(@OLD_FOREIGN_KEY_CHECKS IS NULL, 1, @OLD_FOREIGN_KEY_CHECKS) <em>/;<br>/</em>!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;</p>
<pre><code>### 测试Code</code></pre><p>package com.imgurl;</p>
<p>import com.alibaba.druid.pool.DruidDataSource;<br>import org.apache.shiro.SecurityUtils;<br>import org.apache.shiro.authc.AuthenticationException;<br>import org.apache.shiro.authc.UsernamePasswordToken;<br>import org.apache.shiro.mgt.DefaultSecurityManager;<br>import org.apache.shiro.subject.Subject;<br>import org.junit.Test;<br>import org.apache.shiro.realm.jdbc.JdbcRealm;</p>
<p>import java.util.Arrays;</p>
<p>public class TestJdbcRealm {<br>    DruidDataSource datasource = new DruidDataSource();<br>    {<br>        datasource.setUrl(“jdbc:mysql://localhost:3306/test”);<br>        datasource.setUsername(“root”);<br>        datasource.setPassword(“root”);<br>    }</p>
<pre><code>@Test
public void JdbcRealmTest(){</code></pre><p>//        1.创建JdbcRealm<br>        JdbcRealm jdbcRealm = new JdbcRealm();<br>        jdbcRealm.setDataSource(datasource);  //设置数据源<br>        jdbcRealm.setPermissionsLookupEnabled(true);  //设置可查看用户权限</p>
<p>//        2.创建安全管理器<br>        DefaultSecurityManager defaultSecurityManager = new DefaultSecurityManager();<br>        defaultSecurityManager.setRealm(jdbcRealm);</p>
<p>//        3.主题请求<br>        SecurityUtils.setSecurityManager(defaultSecurityManager);<br>        Subject subject = SecurityUtils.getSubject();</p>
<p>//        4.用户认证<br>        UsernamePasswordToken token = new UsernamePasswordToken(“admin”,”123456”);<br>        try {<br>            subject.login(token);<br>            System.out.println(“登录成功”);</p>
<pre><code>        System.out.println(&quot;--------角色验证---------&quot;);
        System.out.println(&quot;是否具备Manger权限：&quot;+subject.hasRole(&quot;Manager&quot;));
        System.out.println(&quot;是否具备Otheruser权限：&quot;+subject.hasRole(&quot;Otheruser&quot;));
        System.out.println(&quot;是否同事具备Manger和Otheruser权限：&quot;+subject.hasAllRoles(Arrays.asList(&quot;Manager&quot;,&quot;Otheruser&quot;)));

        System.out.println(&quot;---------权限------------&quot;);
        System.out.println(&quot;是否具备user:select权限：&quot;+subject.isPermitted(&quot;user:select&quot;));
        System.out.println(&quot;是否具备user:add权限：&quot;+subject.isPermitted(&quot;user:add&quot;));
        System.out.println(&quot;是否具备user:delete权限：&quot;+subject.isPermitted(&quot;user:delete&quot;));
        System.out.println(&quot;是否具备user:update权限：&quot;+subject.isPermitted(&quot;user:update&quot;));
    }catch (AuthenticationException e){
        e.printStackTrace();
        System.out.println(&quot;登录失败&quot;);
    }
}</code></pre><p>}</p>
<pre><code></code></pre><p>登录成功<br>——–角色验证———<br>是否具备Manger权限：true<br>是否具备Otheruser权限：false<br>是否同事具备Manger和Otheruser权限：false<br>———权限————<br>是否具备user:select权限：true<br>是否具备user:add权限：true<br>是否具备user:delete权限：true<br>是否具备user:update权限：true</p>
<pre><code>你会发现我们利用数据库也发现有mysql语句啊。因为我们使用了JdbcRealm的内置语句。我们是按照它语句来命名数据表字段的。下面是代码片段
&gt;  JdbcRealm.class  </code></pre><p>public class JdbcRealm extends AuthorizingRealm {<br>    protected static final String DEFAULT_AUTHENTICATION_QUERY = “select password from users where username = ?”;<br>    protected static final String DEFAULT_SALTED_AUTHENTICATION_QUERY = “select password, password_salt from users where username = ?”;<br>    protected static final String DEFAULT_USER_ROLES_QUERY = “select role_name from user_roles where username = ?”;<br>    protected static final String DEFAULT_PERMISSIONS_QUERY = “select permission from roles_permissions where role_name = ?”;<br>    private static final Logger log = LoggerFactory.getLogger(JdbcRealm.class);<br>    protected DataSource dataSource;<br>    protected String authenticationQuery = “select password from users where username = ?”;<br>    protected String userRolesQuery = “select role_name from user_roles where username = ?”;<br>    protected String permissionsQuery = “select permission from roles_permissions where role_name = ?”;<br>    protected boolean permissionsLookupEnabled = false;<br>    protected JdbcRealm.SaltStyle saltStyle;</p>
<pre><code>### 自定义数据库及语句
#### 创建新表</code></pre><hr>
<p>– 主机:                           127.0.0.1<br>– 服务器版本:                        10.3.10-MariaDB - mariadb.org binary distribution<br>– 服务器操作系统:                      Win64<br>– HeidiSQL 版本:                  9.4.0.5125</p>
<hr>
<p>/<em>!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;<br>/</em>!40101 SET NAMES utf8 <em>/;<br>/</em>!50503 SET NAMES utf8mb4 <em>/;<br>/</em>!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 <em>/;<br>/</em>!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE=’NO_AUTO_VALUE_ON_ZERO’ */;</p>
<p>– 导出  表 shirotest.sys_permissions 结构<br>CREATE TABLE IF NOT EXISTS <code>sys_permissions</code> (<br>  <code>id</code> int(11) NOT NULL AUTO_INCREMENT,<br>  <code>role_name</code> varchar(50) DEFAULT ‘0’,<br>  <code>permission</code> varchar(50) DEFAULT ‘0’,<br>  PRIMARY KEY (<code>id</code>),<br>  UNIQUE KEY <code>permissions</code> (<code>role_name</code>,<code>permission</code>)<br>) ENGINE=InnoDB AUTO_INCREMENT=21 DEFAULT CHARSET=latin1;</p>
<p>– 正在导出表  shirotest.sys_permissions 的数据：~2 rows (大约)<br>/<em>!40000 ALTER TABLE <code>sys_permissions</code> DISABLE KEYS */;<br>INSERT INTO <code>sys_permissions</code> (<code>id</code>, <code>role_name</code>, <code>permission</code>) VALUES<br>    (1, ‘root’, ‘user:add’),<br>    (2, ‘root’, ‘user:delete’),<br>    (4, ‘root’, ‘user:select’),<br>    (3, ‘root’, ‘user:update’),<br>    (5, ‘user’, ‘user:select’);<br>/</em>!40000 ALTER TABLE <code>sys_permissions</code> ENABLE KEYS */;</p>
<p>– 导出  表 shirotest.sys_roles 结构<br>CREATE TABLE IF NOT EXISTS <code>sys_roles</code> (<br>  <code>id</code> int(11) NOT NULL AUTO_INCREMENT COMMENT ‘ID’,<br>  <code>username</code> varchar(50) NOT NULL DEFAULT ‘0’ COMMENT ‘用户名’,<br>  <code>role_name</code> varchar(50) NOT NULL DEFAULT ‘0’ COMMENT ‘角色名称’,<br>  PRIMARY KEY (<code>id</code>),<br>  UNIQUE KEY <code>username_rolename</code> (<code>username</code>,<code>role_name</code>)<br>) ENGINE=InnoDB AUTO_INCREMENT=3 DEFAULT CHARSET=latin1;</p>
<p>– 正在导出表  shirotest.sys_roles 的数据：~2 rows (大约)<br>/<em>!40000 ALTER TABLE <code>sys_roles</code> DISABLE KEYS */;<br>INSERT INTO <code>sys_roles</code> (<code>id</code>, <code>username</code>, <code>role_name</code>) VALUES<br>    (1, ‘admin’, ‘root’),<br>    (2, ‘fun’, ‘user’);<br>/</em>!40000 ALTER TABLE <code>sys_roles</code> ENABLE KEYS */;</p>
<p>– 导出  表 shirotest.sys_users 结构<br>CREATE TABLE IF NOT EXISTS <code>sys_users</code> (<br>  <code>id</code> int(11) NOT NULL AUTO_INCREMENT COMMENT ‘用户ID’,<br>  <code>username</code> varchar(50) NOT NULL DEFAULT ‘0’ COMMENT ‘用户名’,<br>  <code>password</code> varchar(50) NOT NULL DEFAULT ‘0’ COMMENT ‘用户密码’,<br>  <code>salt</code> varchar(100) NOT NULL DEFAULT ‘0’ COMMENT ‘盐值’,<br>  <code>last_ip</code> varchar(100) NOT NULL DEFAULT ‘0’ COMMENT ‘最后登录IP’,<br>  PRIMARY KEY (<code>id</code>),<br>  UNIQUE KEY <code>user_username</code> (<code>username</code>)<br>) ENGINE=InnoDB AUTO_INCREMENT=3 DEFAULT CHARSET=latin1;</p>
<p>– 正在导出表  shirotest.sys_users 的数据：~2 rows (大约)<br>/<em>!40000 ALTER TABLE <code>sys_users</code> DISABLE KEYS */;<br>INSERT INTO <code>sys_users</code> (<code>id</code>, <code>username</code>, <code>password</code>, <code>salt</code>, <code>last_ip</code>) VALUES<br>    (1, ‘admin’, ‘123456’, ‘0’, ‘0’),<br>    (2, ‘fun’, ‘123456’, ‘0’, ‘0’);<br>/</em>!40000 ALTER TABLE <code>sys_users</code> ENABLE KEYS */;</p>
<p>/<em>!40101 SET SQL_MODE=IFNULL(@OLD_SQL_MODE, ‘’) */;<br>/</em>!40014 SET FOREIGN_KEY_CHECKS=IF(@OLD_FOREIGN_KEY_CHECKS IS NULL, 1, @OLD_FOREIGN_KEY_CHECKS) <em>/;<br>/</em>!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;</p>
<pre><code>其实数据库都差不多，只是没有按照内置的命名。
### 测试Code</code></pre><p>package com.imgurl;</p>
<p>import com.alibaba.druid.pool.DruidDataSource;<br>import org.apache.shiro.SecurityUtils;<br>import org.apache.shiro.authc.AuthenticationException;<br>import org.apache.shiro.authc.UsernamePasswordToken;<br>import org.apache.shiro.mgt.DefaultSecurityManager;<br>import org.apache.shiro.realm.jdbc.JdbcRealm;<br>import org.apache.shiro.subject.Subject;<br>import org.junit.Test;</p>
<p>import java.util.Arrays;</p>
<p>public class CustomizeJdbcRealm {<br>    DruidDataSource datasource = new DruidDataSource();<br>    {<br>        datasource.setUrl(“jdbc:mysql://localhost:3306/shirotest”);<br>        datasource.setUsername(“root”);<br>        datasource.setPassword(“root”);<br>    }</p>
<pre><code>@Test
public void CustomizeJdbcRealmTest(){</code></pre><p>//        1.创建JdbcRealm<br>        JdbcRealm jdbcRealm = new JdbcRealm();<br>        jdbcRealm.setDataSource(datasource);<br>        jdbcRealm.setPermissionsLookupEnabled(true);</p>
<pre><code>    String sql = &quot;select password from sys_users where username = ?&quot;;
    jdbcRealm.setAuthenticationQuery(sql);

    String rolesql = &quot;select role_name from sys_roles where username = ?&quot;;
    jdbcRealm.setUserRolesQuery(rolesql);

    String permissionsql = &quot;select permission from sys_permissions where role_name = ?&quot;;
    jdbcRealm.setPermissionsQuery(permissionsql);</code></pre><p>//        2.创建安全管理器<br>        DefaultSecurityManager defaultSecurityManager = new DefaultSecurityManager();<br>        defaultSecurityManager.setRealm(jdbcRealm);</p>
<p>//        2.主体请求<br>        SecurityUtils.setSecurityManager(defaultSecurityManager);<br>        Subject subject = SecurityUtils.getSubject();</p>
<p>//        3.认证<br>        UsernamePasswordToken token = new UsernamePasswordToken(“fun”,”123456”);<br>        try {<br>            subject.login(token);</p>
<pre><code>        System.out.println(&quot;认证是否成功：&quot;+subject.isAuthenticated());

        System.out.println(&quot;--------角色验证---------&quot;);
        System.out.println(&quot;是否具备root权限：&quot;+subject.hasRole(&quot;root&quot;));
        System.out.println(&quot;是否具备user权限：&quot;+subject.hasRole(&quot;user&quot;));
        System.out.println(&quot;是否同事具备root和user权限：&quot;+subject.hasAllRoles(Arrays.asList(&quot;root&quot;,&quot;user&quot;)));
        System.out.println(&quot;---------权限------------&quot;);
        System.out.println(&quot;是否具备user:select权限：&quot;+subject.isPermitted(&quot;user:select&quot;));
        System.out.println(&quot;是否具备user:add权限：&quot;+subject.isPermitted(&quot;user:add&quot;));
        System.out.println(&quot;是否具备user:delete权限：&quot;+subject.isPermitted(&quot;user:delete&quot;));
        System.out.println(&quot;是否具备user:update权限：&quot;+subject.isPermitted(&quot;user:update&quot;));
    }catch (AuthenticationException e) {
        e.printStackTrace();
        System.out.println(&quot;认证失败&quot;);
    }
}</code></pre><p>}</p>
<pre><code></code></pre><p>认证是否成功：true<br>——–角色验证———<br>是否具备root权限：false<br>是否具备user权限：true<br>是否同事具备root和user权限：false<br>———权限————<br>是否具备user:select权限：true<br>是否具备user:add权限：false<br>是否具备user:delete权限：false<br>是否具备user:update权限：false<br>```</p>

            </div>
            <hr/>

            

            <link rel="stylesheet" type="text/css" href="/libs/share/css/share.min.css">

<div id="article-share">
    
    
    <div class="social-share" data-sites="qq,qzone,wechat,weibo,douban" data-wechat-qrcode-helper="<p>微信扫一扫即可分享！</p>"></div>
    <script src="/libs/share/js/social-share.min.js"></script>
    

    

</div>


            

    <div class="reprint" id="reprint-statement">
        <!-- <p class="reprint-tip">
            <i class="fas fa-exclamation-triangle"></i>&nbsp;&nbsp;
            <span>转载规则</span>
        </p> -->
        
            <!-- <div class="center-align">
                <a rel="license" href="https://creativecommons.org/licenses/by-nc-sa/4.0/deed.zh" target="_blank">
                    <img alt="知识共享许可协议"
                         style="border-width:0"
                         src="https://i.creativecommons.org/l/by-nc-sa/4.0/88x31.png"/>
                </a>
            </div> -->
            <br/>
            <a  href="/2019/05/08/shironoji-chu-zhi-shi/">
                《Shiroの基础知识》
            </a> 由
            <a href="https://kalifun.github.io">
                kalifun
            </a> 采用
            <a rel="license" href="https://creativecommons.org/licenses/by/4.0/deed.zh" target="_blank">
                知识共享署名 4.0 国际许可协议
            </a>进行许可。
        
    </div>

    <script async defer>
      document.addEventListener("copy", function (e) {
        let toastHTML = '<span>复制成功，请遵循本文的转载规则</span><button class="btn-flat toast-action" onclick="navToReprintStatement()" style="font-size: smaller">查看</a>';
        M.toast({html: toastHTML})
      });

      function navToReprintStatement() {
        $("html, body").animate({scrollTop: $("#reprint-statement").offset().top - 80}, 800);
      }
    </script>


        </div>
    </div>

    

    

    

    

    
        <style>
    .valine-card {
        margin: 1.5rem auto;
    }

    .valine-card .card-content {
        padding: 20px 20px 5px 20px;
    }

    #vcomments textarea {
        box-sizing: border-box;
        background: url("/medias/comment_bg.png") 100% 100% no-repeat;
    }

    #vcomments p {
        margin: 2px 2px 10px;
        font-size: 1.05rem;
        line-height: 1.78rem;
    }

    #vcomments blockquote p {
        text-indent: 0.2rem;
    }

    #vcomments a {
        padding: 0 2px;
        color: #42b983;
        font-weight: 500;
        text-decoration: underline;
    }

    #vcomments img {
        max-width: 100%;
        height: auto;
        cursor: pointer;
    }

    #vcomments ol li {
        list-style-type: decimal;
    }

    #vcomments ol,
    ul {
        display: block;
        padding-left: 2em;
        word-spacing: 0.05rem;
    }

    #vcomments ul li,
    ol li {
        display: list-item;
        line-height: 1.8rem;
        font-size: 1rem;
    }

    #vcomments ul li {
        list-style-type: disc;
    }

    #vcomments ul ul li {
        list-style-type: circle;
    }

    #vcomments table, th, td {
        padding: 12px 13px;
        border: 1px solid #dfe2e5;
    }

    #vcomments table, th, td {
        border: 0;
    }

    table tr:nth-child(2n), thead {
        background-color: #fafafa;
    }

    #vcomments table th {
        background-color: #f2f2f2;
        min-width: 80px;
    }

    #vcomments table td {
        min-width: 80px;
    }

    #vcomments h1 {
        font-size: 1.85rem;
        font-weight: bold;
        line-height: 2.2rem;
    }

    #vcomments h2 {
        font-size: 1.65rem;
        font-weight: bold;
        line-height: 1.9rem;
    }

    #vcomments h3 {
        font-size: 1.45rem;
        font-weight: bold;
        line-height: 1.7rem;
    }

    #vcomments h4 {
        font-size: 1.25rem;
        font-weight: bold;
        line-height: 1.5rem;
    }

    #vcomments h5 {
        font-size: 1.1rem;
        font-weight: bold;
        line-height: 1.4rem;
    }

    #vcomments h6 {
        font-size: 1rem;
        line-height: 1.3rem;
    }

    #vcomments p {
        font-size: 1rem;
        line-height: 1.5rem;
    }

    #vcomments hr {
        margin: 12px 0;
        border: 0;
        border-top: 1px solid #ccc;
    }

    #vcomments blockquote {
        margin: 15px 0;
        border-left: 5px solid #42b983;
        padding: 1rem 0.8rem 0.3rem 0.8rem;
        color: #666;
        background-color: rgba(66, 185, 131, .1);
    }

    #vcomments pre {
        font-family: monospace, monospace;
        padding: 1.2em;
        margin: .5em 0;
        background: #272822;
        overflow: auto;
        border-radius: 0.3em;
        tab-size: 4;
    }

    #vcomments code {
        font-family: monospace, monospace;
        padding: 1px 3px;
        font-size: 0.92rem;
        color: #e96900;
        background-color: #f8f8f8;
        border-radius: 2px;
    }

    #vcomments pre code {
        font-family: monospace, monospace;
        padding: 0;
        color: #e8eaf6;
        background-color: #272822;
    }

    #vcomments pre[class*="language-"] {
        padding: 1.2em;
        margin: .5em 0;
    }

    #vcomments code[class*="language-"],
    pre[class*="language-"] {
        color: #e8eaf6;
    }

    #vcomments [type="checkbox"]:not(:checked), [type="checkbox"]:checked {
        position: inherit;
        margin-left: -1.3rem;
        margin-right: 0.4rem;
        margin-top: -1px;
        vertical-align: middle;
        left: unset;
        visibility: visible;
    }

    #vcomments b,
    strong {
        font-weight: bold;
    }

    #vcomments dfn {
        font-style: italic;
    }

    #vcomments small {
        font-size: 85%;
    }

    #vcomments cite {
        font-style: normal;
    }

    #vcomments mark {
        background-color: #fcf8e3;
        padding: .2em;
    }

    #vcomments table, th, td {
        padding: 12px 13px;
        border: 1px solid #dfe2e5;
    }

    table tr:nth-child(2n), thead {
        background-color: #fafafa;
    }

    #vcomments table th {
        background-color: #f2f2f2;
        min-width: 80px;
    }

    #vcomments table td {
        min-width: 80px;
    }

    #vcomments [type="checkbox"]:not(:checked), [type="checkbox"]:checked {
        position: inherit;
        margin-left: -1.3rem;
        margin-right: 0.4rem;
        margin-top: -1px;
        vertical-align: middle;
        left: unset;
        visibility: visible;
    }
</style>

<div class="card valine-card" data-aos="fade-up">
    <div id="vcomments" class="card-content"></div>
</div>

<script src="/libs/valine/av-min.js"></script>
<script src="https://unpkg.com/valine@1.3.10/dist/Valine.min.js"></script>
<script>
    new Valine({
        el: '#vcomments',
        appId: 'iraN3jfhmm5j0LEUAiIKqKCG-gzGzoHsz',
        appKey: 'z0VM1V16mtmP6AMrCtxOK4wy',
        notify: 'false' === 'true',
        verify: 'false' === 'true',
        visitor: 'true' === 'true',
        avatar: 'mm',
        pageSize: '10',
        lang: 'zh-cn',
        placeholder: 'just go go'
    });
</script>

    

    

<article id="prenext-posts" class="prev-next articles">
    <div class="row article-row">
        
        <div class="article col s12 m6" data-aos="fade-up">
            <div class="article-badge left-badge text-color">
                <i class="fas fa-chevron-left"></i>&nbsp;上一篇</div>
            <div class="card">
                <a href="/2019/05/08/dai-ma-zi-dong-sheng-cheng-qi-nogeneratorconfig/">
                    <div class="card-image">
                        
                        
                        <img src="/medias/featureimages/5.jpg" class="responsive-img" alt="代码自动生成器のgeneratorconfig.xml">
                        
                        <span class="card-title">代码自动生成器のgeneratorconfig.xml</span>
                    </div>
                </a>
                <div class="card-content article-content">
                    <div class="summary block-with-text">
                        
                            代码自动生成器のgeneratorconfig.xml前言
当我们写Java项目的时候，我们和数据相关时必定要写Dao，DaoMapper，Model相关的实体和接口。我觉得很无脑的敲，虽然很多都有补全，但是感觉还是没有自动生成快。

配置
                        
                    </div>
                    <div class="publish-info">
                        <span class="publish-date">
                            <i class="far fa-clock fa-fw icon-date"></i>2019-05-08
                        </span>
                        <span class="publish-author">
                            
                            <i class="fas fa-bookmark fa-fw icon-category"></i>
                            
                            <a href="/categories/Java/" class="post-category">
                                    Java
                                </a>
                            
                            
                        </span>
                    </div>
                </div>
                
                <div class="card-action article-tags">
                    
                    <a href="/tags/springboot/">
                        <span class="chip bg-color">springboot</span>
                    </a>
                    
                </div>
                
            </div>
        </div>
        
        
        <div class="article col s12 m6" data-aos="fade-up">
            <div class="article-badge right-badge text-color">
                下一篇&nbsp;<i class="fas fa-chevron-right"></i>
            </div>
            <div class="card">
                <a href="/2019/05/05/javanoimgurl/">
                    <div class="card-image">
                        
                        
                        <img src="/medias/featureimages/4.jpg" class="responsive-img" alt="JavaのImgUrl">
                        
                        <span class="card-title">JavaのImgUrl</span>
                    </div>
                </a>
                <div class="card-content article-content">
                    <div class="summary block-with-text">
                        
                            JavaのImgUrl简介简单的一个图床网站。需要注册才能上传文件，管理员可以无限制的上传图片，普通注册用户一天只能5张图片。
创建环境
编辑器：IDEA
数据库：MariaDB
后端框架：SSM+Shiro
前端框架：Boostrap +
                        
                    </div>
                    <div class="publish-info">
                            <span class="publish-date">
                                <i class="far fa-clock fa-fw icon-date"></i>2019-05-05
                            </span>
                        <span class="publish-author">
                            
                            <i class="fas fa-bookmark fa-fw icon-category"></i>
                            
                            <a href="/categories/Java/" class="post-category">
                                    Java
                                </a>
                            
                            
                        </span>
                    </div>
                </div>
                
                <div class="card-action article-tags">
                    
                    <a href="/tags/springboot/">
                        <span class="chip bg-color">springboot</span>
                    </a>
                    
                </div>
                
            </div>
        </div>
        
    </div>
</article>

</div>


<script>
    $('#articleContent').on('copy', function (e) {
        // IE8 or earlier browser is 'undefined'
        if (typeof window.getSelection === 'undefined') return;

        var selection = window.getSelection();
        // if the selection is short let's not annoy our users.
        if (('' + selection).length < Number.parseInt('120')) {
            return;
        }

        // create a div outside of the visible area and fill it with the selected text.
        var bodyElement = document.getElementsByTagName('body')[0];
        var newdiv = document.createElement('div');
        newdiv.style.position = 'absolute';
        newdiv.style.left = '-99999px';
        bodyElement.appendChild(newdiv);
        newdiv.appendChild(selection.getRangeAt(0).cloneContents());

        // we need a <pre> tag workaround.
        // otherwise the text inside "pre" loses all the line breaks!
        if (selection.getRangeAt(0).commonAncestorContainer.nodeName === 'PRE') {
            newdiv.innerHTML = "<pre>" + newdiv.innerHTML + "</pre>";
        }

        var url = document.location.href;
        newdiv.innerHTML += '<br />'
            + '来源: kalifun<br />'
            + '作者: kalifun<br />'
            + '链接: <a href="' + url + '">' + url + '</a><br />'
            + '本文章著作权归作者所有，任何形式的转载都请注明出处。';

        selection.selectAllChildren(newdiv);
        window.setTimeout(function () {bodyElement.removeChild(newdiv);}, 200);
    });
</script>


    </div>
    <div id="toc-aside" class="expanded col l3 hide-on-med-and-down">
        <div class="toc-widget">
            <div class="toc-title"><i class="far fa-list-alt"></i>&nbsp;&nbsp;目录</div>
            <div id="toc-content"></div>
        </div>
    </div>
</div>

<!-- TOC 悬浮按钮. -->

<div id="floating-toc-btn" class="hide-on-med-and-down">
    <a class="btn-floating btn-large bg-color">
        <i class="fas fa-list-ul"></i>
    </a>
</div>


<script src="/libs/tocbot/tocbot.min.js"></script>
<script>
    $(function () {
        tocbot.init({
            tocSelector: '#toc-content',
            contentSelector: '#articleContent',
            headingsOffset: -($(window).height() * 0.4 - 45),
            // headingsOffset: -205,
            headingSelector: 'h2, h3, h4'
        });

        // modify the toc link href to support Chinese.
        let i = 0;
        let tocHeading = 'toc-heading-';
        $('#toc-content a').each(function () {
            $(this).attr('href', '#' + tocHeading + (++i));
        });

        // modify the heading title id to support Chinese.
        i = 0;
        $('#articleContent').children('h2, h3, h4').each(function () {
            $(this).attr('id', tocHeading + (++i));
        });

        // Set scroll toc fixed.
        let tocHeight = parseInt($(window).height() * 0.4 - 64);
        let $tocWidget = $('.toc-widget');
        $(window).scroll(function () {
            let scroll = $(window).scrollTop();
            /* add post toc fixed. */
            if (scroll > tocHeight) {
                $tocWidget.addClass('toc-fixed');
            } else {
                $tocWidget.removeClass('toc-fixed');
            }
        });

        
        /* 修复文章卡片 div 的宽度. */
        let fixPostCardWidth = function (srcId, targetId) {
            let srcDiv = $('#' + srcId);
            if (srcDiv.length === 0) {
                return;
            }

            let w = srcDiv.width();
            if (w >= 450) {
                w = w + 21;
            } else if (w >= 350 && w < 450) {
                w = w + 18;
            } else if (w >= 300 && w < 350) {
                w = w + 16;
            } else {
                w = w + 14;
            }
            $('#' + targetId).width(w);
        };

        // 切换TOC目录展开收缩的相关操作.
        const expandedClass = 'expanded';
        let $tocAside = $('#toc-aside');
        let $mainContent = $('#main-content');
        $('#floating-toc-btn .btn-floating').click(function () {
            if ($tocAside.hasClass(expandedClass)) {
                $tocAside.removeClass(expandedClass).slideUp(500);
                $mainContent.removeClass('l9');
            } else {
                $tocAside.addClass(expandedClass).slideDown(500);
                $mainContent.addClass('l9');
            }
            fixPostCardWidth('artDetail', 'prenext-posts');
        });
        
    });
</script>

    

</main>



    <footer class="page-footer bg-color">
    <div class="container row center-align">
        <div class="col s12 m8 l8 copy-right">
            Copyright&nbsp;&copy;
            <span id="year">年份</span>
            <a href="https://kalifun.github.io" target="_blank">kalifun</a>
            |&nbsp;Powered by&nbsp;<a href="https://hexo.io/" target="_blank">Hexo</a>
            |&nbsp;Theme&nbsp;<a href="https://github.com/blinkfox/hexo-theme-matery" target="_blank">Matery</a>
            <br>
            
            &nbsp;<i class="fas fa-chart-area"></i>&nbsp;站点总字数:&nbsp;<span
                class="white-color">59.8k</span>&nbsp;字
            
            
            
            
            
            
            <span id="busuanzi_container_site_pv">
                |&nbsp;<i class="far fa-eye"></i>&nbsp;总访问量:&nbsp;<span id="busuanzi_value_site_pv"
                    class="white-color"></span>&nbsp;次
            </span>
            
            
            <span id="busuanzi_container_site_uv">
                |&nbsp;<i class="fas fa-users"></i>&nbsp;总访问人数:&nbsp;<span id="busuanzi_value_site_uv"
                    class="white-color"></span>&nbsp;人
            </span>
            
            <br>
            <span id="sitetime">载入运行时间...</span>
            <script>
                function siteTime() {
                    window.setTimeout("siteTime()", 1000);
                    var seconds = 1000;
                    var minutes = seconds * 60;
                    var hours = minutes * 60;
                    var days = hours * 24;
                    var years = days * 365;
                    var today = new Date();
                    var startYear = "2020";
                    var startMonth = "1";
                    var startDate = "08";
                    var startHour = "0";
                    var startMinute = "0";
                    var startSecond = "0";
                    var todayYear = today.getFullYear();
                    var todayMonth = today.getMonth() + 1;
                    var todayDate = today.getDate();
                    var todayHour = today.getHours();
                    var todayMinute = today.getMinutes();
                    var todaySecond = today.getSeconds();
                    var t1 = Date.UTC(startYear, startMonth, startDate, startHour, startMinute, startSecond);
                    var t2 = Date.UTC(todayYear, todayMonth, todayDate, todayHour, todayMinute, todaySecond);
                    var diff = t2 - t1;
                    var diffYears = Math.floor(diff / years);
                    var diffDays = Math.floor((diff / days) - diffYears * 365);
                    var diffHours = Math.floor((diff - (diffYears * 365 + diffDays) * days) / hours);
                    var diffMinutes = Math.floor((diff - (diffYears * 365 + diffDays) * days - diffHours * hours) /
                        minutes);
                    var diffSeconds = Math.floor((diff - (diffYears * 365 + diffDays) * days - diffHours * hours -
                        diffMinutes * minutes) / seconds);
                    if (startYear == todayYear) {
                        document.getElementById("year").innerHTML = todayYear;
                        document.getElementById("sitetime").innerHTML = "本站已安全运行 " + diffDays + " 天 " + diffHours +
                            " 小时 " + diffMinutes + " 分钟 " + diffSeconds + " 秒";
                    } else {
                        document.getElementById("year").innerHTML = startYear + " - " + todayYear;
                        document.getElementById("sitetime").innerHTML = "本站已安全运行 " + diffYears + " 年 " + diffDays +
                            " 天 " + diffHours + " 小时 " + diffMinutes + " 分钟 " + diffSeconds + " 秒";
                    }
                }
                setInterval(siteTime, 1000);
            </script>
            <br>
            
            <span id="icp"><img src="/medias/icp.png" style="vertical-align: text-bottom;" />
                <a href="https://blog.kalifun.top" target="_blank">赣ICP 18014942号</a>
            </span>
            
        </div>
        <div class="col s12 m4 l4 social-link social-statis">
    <a href="https://github.com/kalifun" class="tooltipped" target="_blank" data-tooltip="访问我的GitHub" data-position="top" data-delay="50">
        <i class="fab fa-github"></i>
    </a>



    <a href="mailto:kalifun@outlook.com" class="tooltipped" target="_blank" data-tooltip="邮件联系我" data-position="top" data-delay="50">
        <i class="fas fa-envelope-open"></i>
    </a>













</div>
    </div>
</footer>

<div class="progress-bar"></div>


    <!-- 搜索遮罩框 -->
<div id="searchModal" class="modal">
    <div class="modal-content">
        <div class="search-header">
            <span class="title"><i class="fas fa-search"></i>&nbsp;&nbsp;搜索</span>
            <input type="search" id="searchInput" name="s" placeholder="请输入搜索的关键字"
                   class="search-input">
        </div>
        <div id="searchResult"></div>
    </div>
</div>

<script src="/js/search.js"></script>
<script type="text/javascript">
$(function () {
    searchFunc("/" + "search.xml", 'searchInput', 'searchResult');
});
</script>
    <!-- 回到顶部按钮 -->
<div id="backTop" class="top-scroll">
    <a class="btn-floating btn-large waves-effect waves-light" href="#!">
        <i class="fas fa-arrow-up"></i>
    </a>
</div>


    <script src="/libs/materialize/materialize.min.js"></script>
    <script src="/libs/masonry/masonry.pkgd.min.js"></script>
    <script src="/libs/aos/aos.js"></script>
    <script src="/libs/scrollprogress/scrollProgress.min.js"></script>
    <script src="/libs/lightGallery/js/lightgallery-all.min.js"></script>
    <script src="/js/matery.js"></script>

    <!-- Global site tag (gtag.js) - Google Analytics -->


    <!-- Baidu Analytics -->


    <!-- Baidu Push -->

<script>
    (function () {
        var bp = document.createElement('script');
        var curProtocol = window.location.protocol.split(':')[0];
        if (curProtocol === 'https') {
            bp.src = 'https://zz.bdstatic.com/linksubmit/push.js';
        } else {
            bp.src = 'http://push.zhanzhang.baidu.com/push.js';
        }
        var s = document.getElementsByTagName("script")[0];
        s.parentNode.insertBefore(bp, s);
    })();
</script>

    
    <script src="/libs/others/clicklove.js" async="async"></script>
    
    
    <script async src="/libs/others/busuanzi.pure.mini.js"></script>
    

    

    

    

    

    
    <script type="text/javascript" src="/libs/background/ribbon-dynamic.js" async="async"></script>
    
    
    

</body>

</html>
